/**
 * Keeps CHANGELOG.md and the What's New data the app renders in step with the
 * pull requests merged into main:
 *
 *   npm run changelog            regenerate both files
 *   npm run changelog -- --digest   print what has merged since the last entry
 *
 * The file has two halves and this script owns exactly one of them.
 *
 * "All changes" is generated: every merged PR, newest first, grouped by the day
 * it merged. It is rebuilt from the GitHub API on every run rather than
 * appended to, so a run that was skipped, or a hand-edit that went wrong, heals
 * itself on the next one. Never edit between its markers; the next run wins.
 *
 * "What's new" is written by hand — by the weekly routine in
 * `.claude/skills/weekly-changelog`, or by anyone fixing its wording. This
 * script only reads it: it copies the block through untouched and derives
 * `src/data/changelog.json` from it. CHANGELOG.md is the source of truth for
 * that prose, so correcting the file is enough and nothing overwrites you.
 *
 * Only "What's new" reaches the app. The generated half is for us — players
 * have no use for a lockfile fix, and there is no reason to ship 110 PR titles
 * to a phone.
 *
 * PRs come from `gh`, which this repo already leans on for everything else
 * (`docs/agents/issue-tracker.md`), so there is no token to plumb through.
 */
import { execFile } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const run = promisify(execFile);

const ROOT = new URL("..", import.meta.url);
const CHANGELOG = fileURLToPath(new URL("CHANGELOG.md", ROOT));
const DATA = fileURLToPath(new URL("src/data/changelog.json", ROOT));

/** Markers around the half this script generates. */
const START = "<!-- all-changes:start -->";
const END = "<!-- all-changes:end -->";
/** Markers around the half people write. */
const NEW_START = "<!-- whats-new:start -->";
const NEW_END = "<!-- whats-new:end -->";

const PREAMBLE = `# Changelog

What has changed in Saturday Slate, newest first.

**What's new** is written for the people playing: the handful of things a member
would notice, in their words. **All changes** is every pull request that landed,
generated by \`npm run changelog\` — do not edit it by hand.
`;

type Pull = {
  number: number;
  title: string;
  mergedAt: string;
  author: string;
  url: string;
};

/**
 * One hand-written entry: the Sunday-to-Saturday span it is labelled with, the
 * moment it was written (`through`; older entries have none), and its bullets.
 */
type Entry = {
  from: string;
  to: string;
  through?: string;
  items: string[];
};

/**
 * Every PR merged into main, newest first.
 *
 * `state=closed` is the whole population — a PR is merged or it is abandoned,
 * and `mergedAt` tells them apart.
 */
async function mergedPulls(repo: string, withBodies = false): Promise<Pull[]> {
  type RawPull = {
    number: number;
    title: string;
    merged_at: string | null;
    user: { login: string } | null;
    html_url: string;
    body: string | null;
  };

  // Pages by number rather than `--paginate`: GitHub's next-page links use
  // `repositories/{id}/...`, which the Claude Code cloud proxy refuses.
  const raw: RawPull[] = [];
  for (let page = 1; ; page++) {
    const { stdout } = await run(
      "gh",
      ["api", `repos/${repo}/pulls?state=closed&base=main&per_page=100&page=${page}`],
      { maxBuffer: 32 * 1024 * 1024 },
    );
    const batch = JSON.parse(stdout) as RawPull[];
    raw.push(...batch);
    if (batch.length < 100) break;
  }

  return raw
    .filter((pull): pull is RawPull & { merged_at: string } => pull.merged_at !== null)
    .map((pull) => ({
      number: pull.number,
      title: pull.title,
      mergedAt: pull.merged_at,
      author: pull.user?.login ?? "",
      url: pull.html_url,
      ...(withBodies ? { body: pull.body } : {}),
    }))
    .sort((a, b) => b.mergedAt.localeCompare(a.mergedAt));
}

/** The day a PR merged, UTC, which is what the API reports. */
function day(mergedAt: string): string {
  return mergedAt.slice(0, 10);
}

/** Markdown for the generated half: a heading per day, a bullet per PR. */
function renderChanges(pulls: Pull[]): string {
  const days = new Map<string, Pull[]>();
  for (const pull of pulls) {
    const existing = days.get(day(pull.mergedAt));
    if (existing) existing.push(pull);
    else days.set(day(pull.mergedAt), [pull]);
  }

  return [...days]
    .map(([date, merged]) => {
      const bullets = merged
        .map((pull) => `- ${pull.title} — [#${pull.number}](${pull.url})`)
        .join("\n");
      return `### ${date}\n\n${bullets}`;
    })
    .join("\n\n");
}

/** The text between two markers, or null when the file has no such block. */
function between(source: string, start: string, end: string): string | null {
  const from = source.indexOf(start);
  const to = source.indexOf(end);
  if (from === -1 || to === -1 || to < from) return null;
  return source.slice(from + start.length, to).trim();
}

/**
 * Reads the hand-written half back out as data.
 *
 * An entry is an ISO date range as its heading and bullets beneath it:
 *
 *     ### 2026-10-04 to 2026-10-10
 *     <!-- through 2026-10-08T23:59:00Z -->
 *     - The Live Board shows possession, down and distance.
 *
 * The range is a Sunday-to-Saturday week, but the routine writes it on the
 * Thursday, so the heading cannot say what the entry covers: a PR that merges
 * on the Friday is inside the range and was never read. The `through` line is
 * when the entry was written, and the next digest starts from it, so a Friday
 * or Saturday merge lands in the following week's entry instead of nowhere.
 * Entries written before the line existed end at the close of their `to` day.
 *
 * The range is deliberately not a Week number. Which Week a span belongs to is
 * a question about published Weeks and their Deadlines, which only the database
 * can answer — so the app resolves it when it renders, where that lookup is
 * already happening, and nothing here has to reach for it.
 */
function parseWhatsNew(block: string): Entry[] {
  const entries: Entry[] = [];
  let current: Entry | null = null;

  for (const line of block.split("\n")) {
    const heading = /^###\s+(\d{4}-\d{2}-\d{2})\s+to\s+(\d{4}-\d{2}-\d{2})\s*$/.exec(line);
    if (heading) {
      current = { from: heading[1], to: heading[2], items: [] };
      entries.push(current);
      continue;
    }
    const bullet = /^[-*]\s+(.*\S)\s*$/.exec(line);
    const through = /^<!--\s*through\s+(\S+)\s*-->\s*$/.exec(line);
    if (through && current) current.through = through[1];
    if (bullet && current) current.items.push(bullet[1]);
  }

  return entries.sort((a, b) => b.to.localeCompare(a.to));
}

/** Prints the PRs a new entry would have to cover, for whoever writes it. */
async function digest(repo: string, entries: Entry[]): Promise<void> {
  const last = entries[0];
  const now = new Date().toISOString().slice(0, 19) + "Z";
  const cutoff = last ? (last.through ?? `${last.to}T23:59:59Z`) : "";
  const pulls = (await mergedPulls(repo, true)).filter(
    (pull) => Date.parse(pull.mergedAt) > Date.parse(cutoff || "1970-01-01T00:00:00Z"),
  );

  if (pulls.length === 0) {
    console.log(
      last
        ? `Nothing has merged since the last entry was written (${cutoff}).`
        : "No pull requests have merged into main yet.",
    );
    return;
  }

  // Entries abut. A run in the week a previous entry already labels writes
  // the next week's entry.
  const from = last ? nextDay(last.to) : sunday(day(pulls[pulls.length - 1].mergedAt));
  const today = day(now);
  const to = saturday(today > from ? today : from);

  console.log(`${pulls.length} pull request(s) merged since the last entry.`);
  console.log(
    `Heading for the new entry, and the line under it, exactly:\n\n### ${from} to ${to}\n<!-- through ${now} -->\n`,
  );
  console.log("---");
  for (const pull of pulls) {
    const body = (pull as Pull & { body?: string }).body?.trim();
    console.log(`\n## #${pull.number} ${pull.title}`);
    console.log(`merged ${pull.mergedAt} by ${pull.author}`);
    if (body) console.log(`\n${body}`);
  }
}

/** An ISO date moved by a number of days. */
function addDays(date: string, days: number): string {
  const next = new Date(`${date}T00:00:00Z`);
  next.setUTCDate(next.getUTCDate() + days);
  return next.toISOString().slice(0, 10);
}

/** The day after an ISO date, so entries abut instead of overlapping. */
function nextDay(date: string): string {
  return addDays(date, 1);
}

/** The Sunday that starts the week an ISO date is in. */
function sunday(date: string): string {
  return addDays(date, -new Date(`${date}T00:00:00Z`).getUTCDay());
}

/** The Saturday that ends the week an ISO date is in. */
function saturday(date: string): string {
  return addDays(sunday(date), 6);
}

async function main() {
  // REST, not `gh repo view`: that one is GraphQL, which Claude Code cloud
  // sessions refuse, and the weekly routine runs in one.
  const { stdout: slug } = await run("gh", ["api", "repos/{owner}/{repo}", "--jq", ".full_name"]);
  const repo = slug.trim();

  const existing = await readFile(CHANGELOG, "utf8").catch(() => "");
  const whatsNew = existing === "" ? null : between(existing, NEW_START, NEW_END);
  const entries = parseWhatsNew(whatsNew ?? "");

  if (process.argv.includes("--digest")) {
    await digest(repo, entries);
    return;
  }

  const pulls = await mergedPulls(repo);
  const kept =
    whatsNew && whatsNew !== ""
      ? whatsNew
      : "_Nothing yet. The weekly routine writes the first entry here._";

  const file = [
    PREAMBLE,
    "\n## What's new\n",
    NEW_START,
    "",
    kept,
    "",
    NEW_END,
    "\n## All changes\n",
    START,
    "",
    renderChanges(pulls),
    "",
    END,
    "",
  ].join("\n");

  await writeFile(CHANGELOG, file);
  await writeFile(
    DATA,
    `${JSON.stringify({ generatedAt: new Date().toISOString(), entries }, null, 2)}\n`,
  );

  console.log(
    `CHANGELOG.md: ${pulls.length} merged pull requests, ${entries.length} What's new entr${entries.length === 1 ? "y" : "ies"}.`,
  );
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
