/**
 * Keeps CHANGELOG.md and the What's New data the app renders in step with the
 * pull requests merged into main:
 *
 *   npm run changelog            regenerate both files
 *   npm run changelog -- --digest   print what has merged since the last entry
 *
 * The file has two halves and this script owns exactly one of them.
 *
 * "All changes" is generated: every merged PR, newest first, grouped by the day
 * it merged. It is rebuilt from the GitHub API on every run rather than
 * appended to, so a run that was skipped, or a hand-edit that went wrong, heals
 * itself on the next one. Never edit between its markers; the next run wins.
 *
 * "What's new" is written by hand — by the weekly routine in
 * `.claude/skills/weekly-changelog`, or by anyone fixing its wording. This
 * script only reads it: it copies the block through untouched and derives
 * `src/data/changelog.json` from it. CHANGELOG.md is the source of truth for
 * that prose, so correcting the file is enough and nothing overwrites you.
 *
 * Only "What's new" reaches the app. The generated half is for us — players
 * have no use for a lockfile fix, and there is no reason to ship 110 PR titles
 * to a phone.
 *
 * PRs come from `gh`, which this repo already leans on for everything else
 * (`docs/agents/issue-tracker.md`), so there is no token to plumb through.
 */
import { execFile } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const run = promisify(execFile);

const ROOT = new URL("..", import.meta.url);
const CHANGELOG = fileURLToPath(new URL("CHANGELOG.md", ROOT));
const DATA = fileURLToPath(new URL("src/data/changelog.json", ROOT));

/** Markers around the half this script generates. */
const START = "<!-- all-changes:start -->";
const END = "<!-- all-changes:end -->";
/** Markers around the half people write. */
const NEW_START = "<!-- whats-new:start -->";
const NEW_END = "<!-- whats-new:end -->";

const PREAMBLE = `# Changelog

What has changed in Saturday Slate, newest first.

**What's new** is written for the people playing: the handful of things a member
would notice, in their words. **All changes** is every pull request that landed,
generated by \`npm run changelog\` — do not edit it by hand.
`;

type Pull = {
  number: number;
  title: string;
  mergedAt: string;
  author: string;
  url: string;
};

/** One hand-written entry: the span it covers, and its bullets. */
type Entry = {
  from: string;
  to: string;
  items: string[];
};

/**
 * Every PR merged into main, newest first.
 *
 * `state=closed` is the whole population — a PR is merged or it is abandoned,
 * and `mergedAt` tells them apart.
 */
async function mergedPulls(repo: string, withBodies = false): Promise<Pull[]> {
  const fields = withBodies
    ? "{number, title, mergedAt: .merged_at, author: .user.login, url: .html_url, body}"
    : "{number, title, mergedAt: .merged_at, author: .user.login, url: .html_url}";
  const { stdout } = await run(
    "gh",
    [
      "api",
      `repos/${repo}/pulls?state=closed&base=main&per_page=100`,
      "--paginate",
      "--jq",
      `.[] | select(.merged_at != null) | ${fields}`,
    ],
    { maxBuffer: 32 * 1024 * 1024 },
  );
  return stdout
    .split("\n")
    .filter((line) => line.trim() !== "")
    .map((line) => JSON.parse(line) as Pull)
    .sort((a, b) => b.mergedAt.localeCompare(a.mergedAt));
}

/** The day a PR merged, UTC, which is what the API reports. */
function day(mergedAt: string): string {
  return mergedAt.slice(0, 10);
}

/** Markdown for the generated half: a heading per day, a bullet per PR. */
function renderChanges(pulls: Pull[]): string {
  const days = new Map<string, Pull[]>();
  for (const pull of pulls) {
    const existing = days.get(day(pull.mergedAt));
    if (existing) existing.push(pull);
    else days.set(day(pull.mergedAt), [pull]);
  }

  return [...days]
    .map(([date, merged]) => {
      const bullets = merged
        .map((pull) => `- ${pull.title} — [#${pull.number}](${pull.url})`)
        .join("\n");
      return `### ${date}\n\n${bullets}`;
    })
    .join("\n\n");
}

/** The text between two markers, or null when the file has no such block. */
function between(source: string, start: string, end: string): string | null {
  const from = source.indexOf(start);
  const to = source.indexOf(end);
  if (from === -1 || to === -1 || to < from) return null;
  return source.slice(from + start.length, to).trim();
}

/**
 * Reads the hand-written half back out as data.
 *
 * An entry is an ISO date range as its heading and bullets beneath it:
 *
 *     ### 2026-09-15 to 2026-09-21
 *     - The Live Board shows possession, down and distance.
 *
 * The range is deliberately not a Week number. Which Week a span belongs to is
 * a question about published Weeks and their Deadlines, which only the database
 * can answer — so the app resolves it when it renders, where that lookup is
 * already happening, and nothing here has to reach for it.
 */
function parseWhatsNew(block: string): Entry[] {
  const entries: Entry[] = [];
  let current: Entry | null = null;

  for (const line of block.split("\n")) {
    const heading = /^###\s+(\d{4}-\d{2}-\d{2})\s+to\s+(\d{4}-\d{2}-\d{2})\s*$/.exec(line);
    if (heading) {
      current = { from: heading[1], to: heading[2], items: [] };
      entries.push(current);
      continue;
    }
    const bullet = /^[-*]\s+(.*\S)\s*$/.exec(line);
    if (bullet && current) current.items.push(bullet[1]);
  }

  return entries.sort((a, b) => b.to.localeCompare(a.to));
}

/** Prints the PRs a new entry would have to cover, for whoever writes it. */
async function digest(repo: string, entries: Entry[]): Promise<void> {
  const since = entries[0]?.to ?? "";
  const pulls = (await mergedPulls(repo, true)).filter((pull) => day(pull.mergedAt) > since);

  if (pulls.length === 0) {
    console.log(
      since === ""
        ? "No pull requests have merged into main yet."
        : `Nothing has merged since the last entry ended (${since}).`,
    );
    return;
  }

  const to = day(pulls[0].mergedAt);
  const from = since === "" ? day(pulls[pulls.length - 1].mergedAt) : nextDay(since);

  console.log(`${pulls.length} pull request(s) merged since the last entry.`);
  console.log(`Heading for the new entry, exactly:\n\n### ${from} to ${to}\n`);
  console.log("---");
  for (const pull of pulls) {
    const body = (pull as Pull & { body?: string }).body?.trim();
    console.log(`\n## #${pull.number} ${pull.title}`);
    console.log(`merged ${pull.mergedAt} by ${pull.author}`);
    if (body) console.log(`\n${body}`);
  }
}

/** The day after an ISO date, so entries abut instead of overlapping. */
function nextDay(date: string): string {
  const next = new Date(`${date}T00:00:00Z`);
  next.setUTCDate(next.getUTCDate() + 1);
  return next.toISOString().slice(0, 10);
}

async function main() {
  const { stdout: slug } = await run("gh", ["repo", "view", "--json", "nameWithOwner", "-q", ".nameWithOwner"]);
  const repo = slug.trim();

  const existing = await readFile(CHANGELOG, "utf8").catch(() => "");
  const whatsNew = existing === "" ? null : between(existing, NEW_START, NEW_END);
  const entries = parseWhatsNew(whatsNew ?? "");

  if (process.argv.includes("--digest")) {
    await digest(repo, entries);
    return;
  }

  const pulls = await mergedPulls(repo);
  const kept =
    whatsNew && whatsNew !== ""
      ? whatsNew
      : "_Nothing yet. The weekly routine writes the first entry here._";

  const file = [
    PREAMBLE,
    "\n## What's new\n",
    NEW_START,
    "",
    kept,
    "",
    NEW_END,
    "\n## All changes\n",
    START,
    "",
    renderChanges(pulls),
    "",
    END,
    "",
  ].join("\n");

  await writeFile(CHANGELOG, file);
  await writeFile(
    DATA,
    `${JSON.stringify({ generatedAt: new Date().toISOString(), entries }, null, 2)}\n`,
  );

  console.log(
    `CHANGELOG.md: ${pulls.length} merged pull requests, ${entries.length} What's new entr${entries.length === 1 ? "y" : "ies"}.`,
  );
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
