#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# Saturday Slate infrastructure provisioning (roadmap ticket #8).
# Run from anywhere: ./scripts/provision-infra.sh
# Re-runnable: stages that are already done can be skipped with "n".

cd "$(dirname "$0")/.."
ENV_FILE=.env.local
REPO="MidfieldMafia/cfb-pickem"
TICKET=8
MAP=1
vc() { npx -y vercel@latest "$@"; }

TOTAL_STAGES=7

banner "Saturday Slate: provision Neon, Vercel, Pingram"

# ── 1. Vercel project ─────────────────────────────────────────────────────
stage "Vercel: create the project from GitHub"
say "Sign in to Vercel with your GitHub account (jonahmabry) and import the repo."
say "The repo is public in the MidfieldMafia org, which is what Hobby requires."
open_url "https://vercel.com/new/import?s=https%3A%2F%2Fgithub.com%2FMidfieldMafia%2Fcfb-pickem"
step "If Vercel asks to install its GitHub app, grant it access to MidfieldMafia/cfb-pickem."
step "Project name: cfb-pickem. Framework preset: Next.js (auto-detected). Leave the rest default."
step "Click Deploy and wait for the first (blank app) deployment to go green."
pause "Deployed? Press Enter."
say "Now link this folder to that project so the CLI can manage env vars."
if [[ -f .vercel/project.json ]]; then
  note "already linked: $(cat .vercel/project.json)"
else
  vc login
  vc link
fi
ask VERCEL_PROD_URL "Production URL shown on the project page (e.g. https://cfb-pickem.vercel.app):"
write_env NEXT_PUBLIC_APP_URL "$VERCEL_PROD_URL"

# ── 2. Neon ───────────────────────────────────────────────────────────────
stage "Neon: Postgres via the Vercel integration"
say "Install Neon from the Vercel Marketplace and attach it to cfb-pickem."
say "This injects DATABASE_URL (pooled) and DATABASE_URL_UNPOOLED (direct) into"
say "every environment and can create a database branch per Preview deployment."
open_url "https://vercel.com/marketplace/neon"
step "Click Install. Choose the Free plan. Region: pick the US region closest to you."
step "When asked which project to connect, pick cfb-pickem, all environments."
step "Open the new database's settings in Vercel (Project → Storage → the Neon store)."
step "Find the preview-branching option (labelled along the lines of"
step "'Create a database branch for each Preview Deployment') and make sure it is on."
note "Neon's console for this database is reachable from the same Storage page ('Open in Neon')."
pause "Neon connected? Press Enter to verify."
vc env pull .env.local --yes >/dev/null 2>&1 || warn "vercel env pull failed; is the folder linked?"
if grep -q '^DATABASE_URL=' .env.local 2>/dev/null && grep -q '^DATABASE_URL_UNPOOLED=' .env.local 2>/dev/null; then
  printf '  %s✓%s DATABASE_URL and DATABASE_URL_UNPOOLED are present in .env.local\n' "$GREEN" "$RESET"
else
  warn "DATABASE_URL / DATABASE_URL_UNPOOLED not found in .env.local"
  SKIPPED+=("Neon env vars missing: re-check the integration attached to cfb-pickem")
fi

# ── 3. CFBD key ───────────────────────────────────────────────────────────
stage "CollegeFootballData API key"
say "Alex holds the CollegeFootballData key (the \$1 tier). Get it from them."
say "It goes into Vercel for Production, Preview, and Development, and never into git."
ask_secret CFBD_API_KEY "Paste the CFBD API key:"
if [[ -n "$CFBD_API_KEY" ]]; then
  vc env add CFBD_API_KEY production,preview,development --value "$CFBD_API_KEY" --sensitive --force >/dev/null \
    && printf '  %s✓ set%s CFBD_API_KEY in Vercel (production, preview, development)\n' "$GREEN" "$RESET" \
    || { warn "vercel env add failed for CFBD_API_KEY"; SKIPPED+=("CFBD_API_KEY in Vercel"); }
  write_env CFBD_API_KEY "$CFBD_API_KEY"
else
  warn "no key entered; skipping"
  SKIPPED+=("CFBD_API_KEY: get it from Alex and run: npx vercel env add CFBD_API_KEY production,preview,development --sensitive")
fi

# ── 4. CRON_SECRET ────────────────────────────────────────────────────────
stage "CRON_SECRET for scheduled endpoints"
say "Scheduled routes (score refresh, reminders) will require this bearer secret."
CRON_SECRET=$(_existing CRON_SECRET || true)
if [[ -z "$CRON_SECRET" ]]; then
  CRON_SECRET=$(openssl rand -hex 32)
  say "Generated a fresh 64-character secret."
else
  note "reusing the CRON_SECRET already in .env.local"
fi
vc env add CRON_SECRET production,preview,development --value "$CRON_SECRET" --sensitive --force >/dev/null \
  && printf '  %s✓ set%s CRON_SECRET in Vercel (production, preview, development)\n' "$GREEN" "$RESET" \
  || { warn "vercel env add failed for CRON_SECRET"; SKIPPED+=("CRON_SECRET in Vercel"); }
write_env CRON_SECRET "$CRON_SECRET"

# ── 5. Alex deploys ───────────────────────────────────────────────────────
stage "Confirm a push by Alex also deploys"
say "On Hobby, commits by someone other than the team owner deploy automatically"
say "only because the repo is public. Alex must also be a repo collaborator."
if command -v gh >/dev/null 2>&1; then
  perm=$(gh api "repos/$REPO/collaborators/AlexMabry/permission" --jq .permission 2>/dev/null || echo "unknown")
  say "AlexMabry's repo permission: $perm"
  [[ "$perm" == "admin" || "$perm" == "write" || "$perm" == "maintain" ]] \
    || warn "Alex needs write access: gh api -X PUT repos/$REPO/collaborators/AlexMabry -f permission=push"
fi
step "Ask Alex to push any branch (even a README tweak) and open a PR."
step "Check the project's Deployments tab for a Preview deployment on that branch."
step "If Vercel instead comments on the PR asking for authorization, click the link once."
open_url "https://vercel.com/dashboard"
if confirm "Did Alex's push produce a Preview deployment?"; then
  ALEX_DEPLOYS="confirmed"
else
  ALEX_DEPLOYS="not yet confirmed"
  SKIPPED+=("Verify a push by Alex produces a Preview deployment")
fi

# ── 6. Pingram ────────────────────────────────────────────────────────────
stage "Pingram: free SMS API key"
say "Texts go through Pingram's free tier: 100 SMS a month from shared numbers,"
say "no card, no carrier registration. The app will not send until the messaging"
say "ticket lands, but the key is captured now so that ticket is not blocked."
open_url "https://www.pingram.io/"
step "Sign up (GitHub or email). Stay on the Free plan; do not add a card."
step "In the dashboard open API Keys and create a secret key (starts with pingram_sk_)."
ask_secret PINGRAM_API_KEY "Paste the Pingram secret API key:"
if [[ -n "$PINGRAM_API_KEY" ]]; then
  vc env add PINGRAM_API_KEY production,preview,development --value "$PINGRAM_API_KEY" --sensitive --force >/dev/null \
    && printf '  %s✓ set%s PINGRAM_API_KEY in Vercel (production, preview, development)\n' "$GREEN" "$RESET" \
    || { warn "vercel env add failed for PINGRAM_API_KEY"; SKIPPED+=("PINGRAM_API_KEY in Vercel"); }
  write_env PINGRAM_API_KEY "$PINGRAM_API_KEY"
  PINGRAM_STATUS="key set in Vercel"
else
  warn "no key entered; skipping"
  SKIPPED+=("PINGRAM_API_KEY: sign up at pingram.io and run: npx vercel env add PINGRAM_API_KEY production,preview,development --sensitive")
  PINGRAM_STATUS="not yet set"
fi
ask PINGRAM_LOGIN "Which email is the Pingram account under?"

# ── 7. Record on the ticket ───────────────────────────────────────────────
stage "Record the outcome on the roadmap ticket"
summary=$(cat <<MD
## Provisioned (via scripts/provision-infra.sh, $(date +%Y-%m-%d))

- **Vercel**: project \`cfb-pickem\` on Jonah's Hobby team, imported from \`$REPO\`. Production: $VERCEL_PROD_URL. Pushes to \`main\` deploy to production; every other branch gets a Preview deployment.
- **Neon**: Free plan, installed through the Vercel Marketplace and attached to the project. \`DATABASE_URL\` (pooled) and \`DATABASE_URL_UNPOOLED\` (direct) are injected into all environments; preview branching is on, so each Preview deployment gets its own database branch.
- **Env vars in Vercel** (Production, Preview, Development): \`CFBD_API_KEY\` (from Alex), \`CRON_SECRET\` (generated), \`PINGRAM_API_KEY\`. Local copies live in \`.env.local\` via \`npx vercel env pull\`.
- **Alex's pushes deploy**: $ALEX_DEPLOYS.
- **Pingram** (free tier, 100 SMS/month, shared sender numbers): account under $PINGRAM_LOGIN; \`PINGRAM_API_KEY\` $PINGRAM_STATUS. No number purchase or carrier verification needed. The Text messaging ticket wires it in.
- **Local setup** is documented in the README.
MD
)
if (( ${#SKIPPED[@]} )); then
  summary+=$'\n\n**Still to do by hand:**\n'
  for s in "${SKIPPED[@]}"; do summary+="- $s"$'\n'; done
fi
printf '%s\n\n' "$summary"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if confirm "Post this as a comment on issue #$TICKET?"; then
    gh issue comment "$TICKET" --repo "$REPO" --body "$summary" >/dev/null && printf '  %s✓ commented%s on #%s\n' "$GREEN" "$RESET" "$TICKET"
    if (( ${#SKIPPED[@]} == 0 )) && confirm "Everything is done. Close #$TICKET and add it to the roadmap's Decisions so far?"; then
      gh issue close "$TICKET" --repo "$REPO" --comment "Resolved: infrastructure provisioned, see the comment above." >/dev/null
      line="- [Task: provision Neon, Vercel, and secrets](https://github.com/$REPO/issues/$TICKET): Vercel project \`cfb-pickem\` at $VERCEL_PROD_URL with Neon Free attached and preview branching on; \`CFBD_API_KEY\` and \`CRON_SECRET\` set in all environments; Pingram free-tier account created and \`PINGRAM_API_KEY\` $PINGRAM_STATUS."
      body_tmp=$(mktemp)
      gh issue view "$MAP" --repo "$REPO" --json body -q .body | tr -d '\r' \
        | awk -v l="$line" '{ a[NR]=$0 } END {
            ins=0; for (i=1;i<=NR;i++) if (a[i] ~ /^## Not yet specified/) { ins=i; break }
            if (ins==0) { for (i=1;i<=NR;i++) print a[i]; print ""; print l; exit }
            j=ins; while (j>1 && a[j-1]=="") j--
            for (i=1;i<j;i++) print a[i]
            print l
            for (i=j;i<=NR;i++) print a[i] }' > "$body_tmp"
      gh issue edit "$MAP" --repo "$REPO" --body-file "$body_tmp" >/dev/null && printf '  %s✓ updated%s roadmap #%s Decisions so far\n' "$GREEN" "$RESET" "$MAP"
      rm -f "$body_tmp"
    else
      note "Leaving #$TICKET open. Re-run this wizard or /wayfinder #$TICKET once the remaining items are done."
    fi
  fi
else
  warn "gh not ready; paste the summary above into https://github.com/$REPO/issues/$TICKET yourself"
fi
# ──────────────────────────────────────────────────────────────────────────

finish
